export const environment = {
  supabaseKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3dHRlYmVqeHduY3B1cnN6emxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDc2MDMxNTAsImV4cCI6MjAyMzE3OTE1MH0.QSw_ggRgiwwLTP9RexPn2UQHPYoN1KWkHs6hq-UZQW4',
  production: true
};
